const dirActionTypes = {
  FETCH_DIRECTORY_START: "FETCH_DIRECTORY_START",
  FETCH_DIRECTORY_SUCCESS: "FETCH_DIRECTORY_SUCCESS",
  FETCH_DIRECTORY_FAILURE: "FETCH_DIRECTORY_SUCCESS",
};

export default dirActionTypes;
