const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_CART: "CLEAR_CART",
  CLEAR_ITEM: "CLEAR_ITEM",
  ADD_ITEM_START: "ADD_ITEM_START",
  ADD_ITEM_SUCCESS: "ADD_ITEM_SUCCESS",
  ADD_ITEM_FAILURE: "ADD_ITEM_FAILURE",
  REMOVE_ITEM_START: "REMOVE_ITEM_START",
  REMOVE_ITEM_SUCCESS: "REMOVE_ITEM_SUCCESS",
  REMOVE_ITEM_FAILURE: "REMOVE_ITEM_FAILURE",
  CLEAR_ITEM_START: "CLEAR_ITEM_START",
  CLEAR_ITEM_SUCCESS: "CLEAR_ITEM_SUCCESS",
  CLEAR_ITEM_FAILURE: "CLEAR_ITEM_FAILURE",
  FETCH_CART_START: "FETCH_CART_START",
  FETCH_CART_SUCCESS: "FETCH_CART_SUCCESS",
  FETCH_CART_FAILURE: "FETCH_CART_FAILURE",
};

export default CartActionTypes;
